"""API schemas for chat and agentic RAG interactions.
This module defines all Pydantic models used as API contracts for chat endpoints,
"""

from datetime import datetime, timezone
from typing import List, Optional, Dict, Any
from enum import Enum

from pydantic import BaseModel, Field, model_validator

from app.models import Citation


class MessageRole(str, Enum):
    """Role of a message in a conversation."""
    
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class ChatMessage(BaseModel):
    """Individual message in a conversation.
    
    Attributes:
        role: The role of the message sender (user, assistant, or system).
        content: The text content of the message.
    """
    
    role: MessageRole = Field(..., description="Role of the message sender")
    content: str = Field(..., min_length=1, description="Message content")


class SearchFilters(BaseModel):
    """Search filters for narrowing results.
    
    Attributes:
        opco_values: Filter by operating company values (REQUIRED).
        persona_values: Filter by persona/audience values (optional).
    """
    
    opco_values: List[str] = Field(
        ...,
        min_length=1,
        description="Filter results by operating company values (e.g., ['teksystems', 'astoncarter'])"
    )
    persona_values: Optional[List[str]] = Field(
        default=None,
        description="Filter results by persona/audience values (e.g., ['front_office', 'producer'])"
    )


class ChatRequest(BaseModel):
    """Request payload for chat endpoint.
    
    Attributes:
        user_id: User identifier for tracking and conversation history.
        message: The user's question or message.
        conversation_history: Optional previous messages for context.
        filters: Optional search filters to narrow results.
        top_k: Number of search results to retrieve for context.
    """

    user_id: Optional[str] = Field(
        default=None,
        description="User identifier for tracking"
    )
    
    message: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="The user's question or message"
    )
    conversation_history: Optional[List[ChatMessage]] = Field(
        default=None,
        max_length=20,
        description="Previous messages in the conversation for context"
    )
    filters: Optional[SearchFilters] = Field(
        default=None,
        description="Optional filters to narrow search results"
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of search results to retrieve for context"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "user_id": "user123",
                    "message": "What are the best practices for Azure Cosmos DB?",
                    "filters": {
                        "opco_values": ["TEKsystems"]
                    },
                    "top_k": 5
                }
            ]
        }
    }


class ChatResponse(BaseModel):
    """Response payload from chat endpoint.
    
    Attributes:
        message: The AI-generated response.
        citations: Source documents used to generate the response.
        timestamp: When the response was generated.
    """
    

    message: str = Field(..., description="The AI-generated response")
    citations: List[Citation] = Field(
        default_factory=list,
        description="Source documents used to generate the response"
    )
    follow_up_questions: List[str] = Field(
        default_factory=list,
        description="List of follow-up questions generated by the LLM"
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When the response was generated"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "message": "Azure Cosmos DB best practices include...",
                    "citations": [
                        {
                            "content_id": "doc-123-chunk-1",
                            "document_title": "Azure Cosmos DB Guide.pdf",
                            "content": "When designing for Cosmos DB, consider partition keys...",
                            "page_number": 5,
                            "relevance_score": 0.92
                        }
                    ],
                    "timestamp": "2026-01-30T10:30:00Z"
                }
            ]
        }
    }


class ConversationMessage(BaseModel):
    """Message in conversation history for agentic RAG workflow.
    
    Attributes:
        role: The role of the message sender (user, assistant, or system).
        content: The text content of the message.
    """
    role: MessageRole = Field(..., description="Role of the message sender")
    content: str = Field(..., min_length=1, description="Message content")


class QueryRequest(BaseModel):
    """Request payload for agentic RAG query endpoint.
    
    Attributes:
        query: The user's question or query.
        session_id: Session ID (must be valid UUID) for conversation context.
        user_id: Optional user identifier (will be pulled from JWT claim when auth is enabled).
        conversation_history: Optional list of previous messages.
        filters: REQUIRED search filters - opco_values must be provided, persona_values is optional.
        stream: Enable streaming response (future enhancement).
    """
    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user's question or query"
    )
    session_id: str = Field(
        ...,
        description="Session ID (must be valid UUID) for conversation context"
    )
    user_id: Optional[str] = Field(
        default=None,
        description="Optional user identifier (will be pulled from JWT claim when auth is enabled)"
    )
    conversation_history: Optional[List[ConversationMessage]] = Field(
        default=None,
        description="Previous messages in the conversation"
    )
    filters: SearchFilters = Field(
        ...,
        description="REQUIRED search filters - opco_values must be provided, persona_values is optional"
    )
    stream: bool = Field(
        default=False,
        description="Enable streaming response (not yet implemented)"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "query": "What are the best practices for Azure Cosmos DB partitioning?",
                    "user_id": "user123",
                    "session_id": "session456",
                    "filters": {
                        "opco_values": ["TEKsystems"],
                        "persona_values": ["Front Office"]
                    },
                    "stream": False
                }
            ]
        }
    }


class QueryResponse(BaseModel):
    """Response payload for agentic RAG query endpoint.
    
    Attributes:
        answer: The generated answer text.
        citations: List of citations with document metadata.
        document_count: Number of documents retrieved.
        session_id: Session ID for this conversation.
        thought_process: Step-by-step workflow execution log with details.
        search_history: History of search attempts with queries and results.
        decisions: List of decisions made by reflection agent per iteration.
        attempts: Number of search attempts made.
        timestamp: Response generation timestamp.
    """
    answer: str = Field(..., description="The generated answer text")
    citations: List[Citation] = Field(
        default_factory=list,
        description="List of citations with document metadata (title, path, relevance score)"
    )
    follow_up_questions: List[str] = Field(
        default_factory=list,
        description="List of follow-up questions generated by the LLM"
    )
    document_count: int = Field(
        default=0,
        description="Number of documents retrieved"
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Session ID for this conversation"
    )
    thought_process: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Step-by-step workflow execution log (retrieve, review, response steps)"
    )
    search_history: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="History of search attempts with queries and result counts"
    )
    decisions: List[str] = Field(
        default_factory=list,
        description="List of decisions made by reflection agent (retry or finalize)"
    )
    attempts: int = Field(
        default=0,
        description="Number of search attempts made"
    )
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="Response generation timestamp"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "answer": "Azure Cosmos DB partitioning best practices include...",
                    "citations": ["doc1", "doc2", "doc3"],
                    "document_count": 5,
                    "session_id": "session456",
                    "thought_process": [
                        {"step": "retrieve", "details": {"results_summary": []}},
                        {"step": "review", "details": {"valid_count": 3}},
                        {"step": "response", "details": {"final_answer": "..."}}
                    ],
                    "search_history": [{"query": "...", "results_count": 10, "attempt": 1}],
                    "decisions": ["finalize"],
                    "attempts": 1
                }
            ]
        }
    }
